on:
  workflow_dispatch:
   inputs:
    webapp:
      type: choice
      description: what environtment to create
      options: 
        - 2022oscardevops-test
        - 2022oscardevops-prod
        - 2022oscardevops-env
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      webapp: 2022oscardevops-test
    steps:
          # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=${{github.event.inputs.webapp }}
